export const ticketsData = [
  {
    id: 1000,
    subject: "Issue 1",
    status: "In Progress",
    support: "Tech support",
    date: "2021-08-01",
    rating: 1,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1001,
    subject: "Issue 2",
    status: "On hold",
    support: "Operation Team",
    date: "2021-08-02",
    rating: 2,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1002,
    subject: "Issue 3",
    status: "Closed",
    support: "Tech support",
    date: "2021-08-03",
    rating: 3,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1003,
    subject: "Issue 4",
    status: "In Progress",
    support: "Operation Team",
    date: "2021-08-04",
    rating: 4,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1004,
    subject: "Issue 5",
    status: "On hold",
    support: "Tech support",
    date: "2021-08-05",
    rating: 5,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1005,
    subject: "Issue 6",
    status: "Closed",
    support: "Operation Team",
    date: "2021-08-06",
    rating: 1,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1006,
    subject: "Issue 7",
    status: "In Progress",
    support: "Tech support",
    date: "2021-08-07",
    rating: 2,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1007,
    subject: "Issue 8",
    status: "On hold",
    support: "Operation Team",
    date: "2021-08-08",
    rating: 3,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1008,
    subject: "Issue 9",
    status: "Closed",
    support: "Tech support",
    date: "2021-08-09",
    rating: 4,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1009,
    subject: "Issue 10",
    status: "In Progress",
    support: "Operation Team",
    date: "2021-08-10",
    rating: 5,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1010,
    subject: "Issue 11",
    status: "On hold",
    support: "Tech support",
    date: "2021-08-11",
    rating: 1,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1011,
    subject: "Issue 12",
    status: "Closed",
    support: "Operation Team",
    date: "2021-08-12",
    rating: 2,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1012,
    subject: "Issue 13",
    status: "In Progress",
    support: "Tech support",
    date: "2021-08-13",
    rating: 3,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1013,
    subject: "Issue 14",
    status: "On hold",
    support: "Operation Team",
    date: "2021-08-14",
    rating: 4,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1014,
    subject: "Issue 15",
    status: "Closed",
    support: "Tech support",
    date: "2021-08-15",
    rating: 5,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1015,
    subject: "Issue 16",
    status: "In Progress",
    support: "Operation Team",
    date: "2021-08-16",
    rating: 1,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1016,
    subject: "Issue 17",
    status: "On hold",
    support: "Tech support",
    date: "2021-08-17",
    rating: 2,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1017,
    subject: "Issue 18",
    status: "Closed",
    support: "Operation Team",
    date: "2021-08-18",
    rating: 3,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1018,
    subject: "Issue 19",
    status: "In Progress",
    support: "Tech support",
    date: "2021-08-19",
    rating: 4,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1019,
    subject: "Issue 20",
    status: "On hold",
    support: "Operation Team",
    date: "2021-08-20",
    rating: 5,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1020,
    subject: "Issue 21",
    status: "Closed",
    support: "Tech support",
    date: "2021-08-21",
    rating: 1,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1021,
    subject: "Issue 22",
    status: "In Progress",
    support: "Operation Team",
    date: "2021-08-22",
    rating: 2,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1022,
    subject: "Issue 23",
    status: "On hold",
    support: "Tech support",
    date: "2021-08-23",
    rating: 3,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1023,
    subject: "Issue 24",
    status: "Closed",
    support: "Operation Team",
    date: "2021-08-24",
    rating: 4,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1024,
    subject: "Issue 25",
    status: "In Progress",
    support: "Tech support",
    date: "2021-08-25",
    rating: 5,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1025,
    subject: "Issue 26",
    status: "On hold",
    support: "Operation Team",
    date: "2021-08-26",
    rating: 1,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1026,
    subject: "Issue 27",
    status: "Closed",
    support: "Tech support",
    date: "2021-08-27",
    rating: 2,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1027,
    subject: "Issue 28",
    status: "In Progress",
    support: "Operation Team",
    date: "2021-08-28",
    rating: 3,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1028,
    subject: "Issue 29",
    status: "On hold",
    support: "Tech support",
    date: "2021-08-29",
    rating: 4,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  },
  {
    id: 1029,
    subject: "Issue 30",
    status: "Closed",
    support: "Operation Team",
    date: "2021-08-30",
    rating: 5,
    name: "",
    department: "",
    title: "",
    description: "",
    category: "",
    type: "",
    priority: "",
    attachment: ""
  }
];
